# Generated by Django 3.2 on 2021-04-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
