# Generated by Django 3.2 on 2021-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gamertag',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='losses',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
