# Generated by Django 3.2 on 2021-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20210416_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='losses',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.FloatField(max_length=15),
        ),
    ]
