# Generated by Django 3.2 on 2021-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_team'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(related_name='teams', to='players.Player'),
        ),
    ]
