# Generated by Django 3.2 on 2021-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_team'),
        ('teams', '0002_team_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='teams', to='players.Player'),
        ),
    ]
