# Generated by Django 3.2 on 2021-04-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        ('teams', '0004_team_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='player',
            new_name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='formation',
        ),
        migrations.AddField(
            model_name='team',
            name='formation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='formations.formation'),
            preserve_default=False,
        ),
    ]
